export const msg = {
    "loginSuccess": "User LoggedIn Successfully",
    "userNotFoundWithSpecifiedID": "User not found with specified Id.",
    "dataFetchSuccess": "Data Fetched Successfully",
    "dataInsertSuccess": "Data Inserted Successfully",
    "dataUpdateSuccess": "Data Updated Successfully",
    "dataDeleteSuccess": "Data Deleted Successfully",
    "invalidId": "Record not found with specified Id",
    "unauthorize": "UNAUTHORIZED",
    "invlidToken": "Token is invalid.",
    "ERROR": "Something went wrong",
    "commonErrorCatch": "Something went wrong",
    "customer": {
        "addsuccess": "Customer added Successfully",
        "roleNameReq": "roleName should not be empty. ",
        "roleName": "Minimum 3 characters and maximum 15 allowed in roleName",
        "roleNameExists": "Role Name already exists"
    },
    "auth": {
        "loggedIn": "Success! You've successfully logged in.",
        "loggedOut": "Success! You've been successfully logged out.",
        "forgetPassword": "Success! Your password has been reset.",
        "resetPassword": "Success! Your password has been reset",
        "emailNotExist": "Email does not exist.",
        "inactive": "User is not active",
        "passwordInvalid": "Invalid Password.",
        "linkSend": "Link and otp send in your registered email address",
        "linkExp": "link is expired",
        "invalidOTP": "Invalid OTP",
        "passMatchConPass": "password and confirm password does not match",
        "emailAlreadyExist": "Email already exist",
        "enterEmail": "Please enter an email",
        "enterUsername": "Please enter username",
        "usernameNotExist": "Username does not exist",
        "usernameAlreadyExist": "Username already exist",
        "usernameDoNotExist": "Username does not exist",
        "deletedUser": "User not currently accessible"
    },
}